### ISSUE TITLE
bug: pip install failed on macOS 

### ISSUE THREAD

**Issue by dragonly** [tensorchord/envd#1061]
## Description
pip install failed on macOS with the Apple M1 Pro chip.

## Reproduction

```
which python3 && python3 --version && python3 -m pip install -U --pre envd
/opt/homebrew/bin/python3
Python 3.10.6
Collecting envd
  Using cached envd-0.2.4a12.tar.gz (245 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      make: *** [build-release] Error 1
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6b/4xcf2vjs2dqbhp_5rxjyp4nm0000gn/T/pip-install-tc9bkg_x/envd_0933e7327b15406e96e2fa43e3e4e4ab/setup.py", line 83, in <module>
          version=get_version(),
        File "/private/var/folders/6b/4xcf2vjs2dqbhp_5rxjyp4nm0000gn/T/pip-install-tc9bkg_x/envd_0933e7327b15406e96e2fa43e3e4e4ab/setup.py", line 58, in get_version
          build_envd_if_not_found()
        File "/private/var/folders/6b/4xcf2vjs2dqbhp_5rxjyp4nm0000gn/T/pip-install-tc9bkg_x/envd_0933e7327b15406e96e2fa43e3e4e4ab/setup.py", line 38, in build_envd_if_not_found
          assert errno == 0, "Failed to build envd"
      AssertionError: Failed to build envd
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
Thanks for the issue!

/cc @VoVAllen

**Comment by gaocegege** [comment]
@all-contributors Please add @dragonly for the bug report.

**Comment by VoVAllen** [comment]
verified the fix on my mac. now it should work
