### ISSUE TITLE
bug(ssh):  Panic error occurs when exiting within the env container

### ISSUE THREAD

**Issue by LuBingtan** [tensorchord/envd#1363]
## Description
Error mesage:
```
[127:NOTFOUND] ⬢ [envd]❯ exit
exit status 127panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105492720]

goroutine 1 [running]:
github.com/tensorchord/envd/pkg/ssh.generalClient.Attach({0x14000053130?, 0x14000c7c240?})
        github.com/tensorchord/envd/pkg/ssh/ssh.go:247 +0x500
github.com/tensorchord/envd/pkg/envd.dockerEngine.Attach({0x1?}, {0x0?, 0x140001fa310?}, {0x1055a2b63, 0x9}, {0x14000040b10?, 0x1400007dbc0?}, 0x105a3d278?, {0x14000153600?, 0x140002b2960?})
        github.com/tensorchord/envd/pkg/envd/docker.go:272 +0xf4
github.com/tensorchord/envd/pkg/app.up(0x14000619f80)
        github.com/tensorchord/envd/pkg/app/up.go:237 +0xae8
github.com/urfave/cli/v2.(*Command).Run(0x1061f0d00, 0x14000619f80, {0x14000119610, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.23.7/command.go:271 +0x78c
github.com/urfave/cli/v2.(*Command).Run(0x14000179540, 0x140006194c0, {0x14000134000, 0x2, 0x2})
        github.com/urfave/cli/v2@v2.23.7/command.go:264 +0x9ac
github.com/urfave/cli/v2.(*App).RunContext(0x140000fe5a0, {0x105a33070?, 0x1400012e008}, {0x14000134000, 0x2, 0x2})
        github.com/urfave/cli/v2@v2.23.7/app.go:333 +0x5dc
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.23.7/app.go:310
main.run({0x14000134000, 0x2, 0x2})
        github.com/tensorchord/envd/cmd/envd/main.go:39 +0x104
main.main()
        github.com/tensorchord/envd/cmd/envd/main.go:67 +0x30
```

## Reproduction
This appears to be an occasional error. Actually, I don't know why there is a 127 exit code here.

But it can be reproduced by killing the `zsh` process inside the container.

## Additional Info
envd version: latest main branch

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by LuBingtan** [comment]
It looks like that this issue is caused by a mistake here:
https://github.com/tensorchord/envd/blob/aae5e27feaa06436fa81c3dc414b28b6b7e21a3b/pkg/ssh/ssh.go#L246-L248

I would like to open a PR to try to fix this
